name: 自动保持

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: # 支持手动随时触发

jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v3

      - name: 'Keepalive Workflow'
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          use_api: false 
